project/tasks/forms.py
# project/tasks/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, DateField, IntegerField, SelectField
from wtforms.validators import DataRequired, Length, EqualTo, Email

class AddTaskForm(FlaskForm):
    task_id = IntegerField()
    name = StringField('Task Name', validators = [DataRequired()])
    due_date = DateField('Due date (dd/mm/yyyy)', validators = [DataRequired()], format='%d/%m/%Y')
    priority = SelectField('Priority', validators = [DataRequired()], choices = [
            ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'),
            ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')
        ])
    status = IntegerField('Status')

project/tasks/views.py
# project/tasks/views.py

import datetime
from functools import wraps
from flask import Flask, flash, redirect, render_template, request, session, url_for, Blueprint
from sqlalchemy.exc import IntegrityError

from .forms import AddTaskForm
from project import db
from project.models import Task

# Config

tasks_blueprint = Blueprint('tasks', __name__)

# Helper functions

def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash("You need to log in first.", "warning")
            return redirect(url_for('users.login'))
    return wrap

def open_tasks():
    return db.session.query(Task).filter_by(status = '1').order_by(Task.due_date.asc())

def closed_tasks():
    return db.session.query(Task).filter_by(status = '0').order_by(Task.due_date.asc())

# Add a new task
def new_task():
    error = None
    form = AddTaskForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_task = Task(
                form.name.data,
                form.due_date.data,
                form.priority.data,
                datetime.datetime.utcnow(),
                '1',
                session['user_id']
                )
            db.session.add(new_task)
            db.session.commit()
            flash('New task created!', 'success')
            return redirect(url_for('tasks.tasks'))
    return render_template('tasks.html', form = form, error = error, open_tasks = open_tasks(), closed_tasks = closed_tasks())

# Routes

# Show tasks
@tasks_blueprint.route('/tasks/', methods = ['GET', 'POST'])
@login_required
def tasks():
    if request.method == 'POST':
        return new_task()
    return render_template('tasks.html',
        form = AddTaskForm(request.form),
        open_tasks = open_tasks(),
        closed_tasks = closed_tasks()
        )

# Complete a task
@tasks_blueprint.route('/complete/<int:task_id>/')
@login_required
def complete(task_id):
    task_to_complete_id = task_id
    task = db.session.query(Task).filter_by(task_id = task_to_complete_id)
    if session['role'] == 'admin' or session['user_id'] == task.first().user_id:
        task.update({'status' : '0'})
        db.session.commit()
        flash('Task is complete. Good job!', 'success')
    else:
        flash('You can only update yours tasks.')
    return redirect(url_for('tasks.tasks'))

# Delete a task
@tasks_blueprint.route('/delete/<int:task_id>/')
@login_required
def delete(task_id):
    task_to_delete_id = task_id
    task = db.session.query(Task).filter_by(task_id = task_to_delete_id)
    if session['role'] == 'admin' or session['user_id'] == task.first().user_id:
        task.delete()
        db.session.commit()
        flash('Task deleted!', 'success')    
    else:
        flash('You can only delete yours tasks.')
    return redirect(url_for('tasks.tasks'))

project/users/views.py
# project/users/views.py

from functools import wraps
from flask import Flask, flash, redirect, render_template, request, session, url_for, Blueprint
from sqlalchemy.exc import IntegrityError

from .forms import RegisterForm, LoginForm
from project import db, bcrypt
from project.models import User
from pprint import pprint

# Config

users_blueprint = Blueprint('users', __name__)

# Helper functions

def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash("You need to log in first.", "warning")
            return redirect(url_for('users.login'))
    return wrap

def guest(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' not in session:
            return test(*args, **kwargs)
        else:
            return redirect(url_for('tasks.tasks'))
    return wrap

# Routes

# Logout
@users_blueprint.route('/logout/')
@login_required
def logout():
    user = User.query.filter_by(user_id = session['user_id']).first()
    flash('Goodbye {}...'.format(user.name), 'info')
    session.pop('logged_in', None)
    session.pop('user_id', None)
    session.pop('role', None)
    session.pop('name', None)
    return redirect(url_for('users.login'))

# Login
@users_blueprint.route('/', methods = ['GET', 'POST'])
@guest
def login():
    error = None
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = User.query.filter_by(name = request.form['name']).first()
            if user is not None and bcrypt.check_password_hash(user.password, request.form['password']):
                session['logged_in'] = True
                session['user_id'] = user.user_id
                session['role'] = user.role
                session['name'] = user.name
                flash('Welcome, {}!'.format(user.name), 'success')
                return redirect(url_for('tasks.tasks'))
            else:
                error = 'Invalid credential. Please try again.'
    return render_template('login.html', form = form, error = error)

# Register
@users_blueprint.route('/register/', methods = ['GET', 'POST'])
@guest
def register():
    error = None
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_user = User(
                form.name.data,
                form.email.data,
                bcrypt.generate_password_hash(form.password.data).decode('utf-8')
                )
            try:
                db.session.add(new_user)
                db.session.commit()
                flash('Registration completed. You can login now!', 'success')
                return redirect(url_for('users.login'))
            except IntegrityError:
                error = 'Username or email already exist.'
    return render_template('register.html', form = form, error = error)

project/templates/_base.html
<!doctype html>
<head>
    <title>Flask Taskr</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">
                    FlaskTaskr
                </a>
            </div>
            <div>
                <div class="nav navbar-nav navbar-right">
                    {% if session.logged_in %}
                        <p class="navbar-text">Welcome, {{ session.name }}</p>
                        <a class="btn btn-primary btn-sm navbar-btn" href="{{ url_for('users.logout') }}">Logout</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="row">
            <div class="alert alert-{{ category }}" role="alert">{{ message }}</div>
        </div>
        {% endfor %}
        {% if error %}
        <div class="row">
            <div class="alert alert-danger" role="alert">{{ error }}</div>
        </div>        
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

project/templates/login.html
{% extends "_base.html" %}
{% block content %}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>Welcome to FlaskTaskr</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                Please log in to access your blog.
            </div>
            <div class="panel-body">
                <form action="" method="POST" class="form-horizontal">
                    {{ form.csrf_token }}
                    <div class="form-group {{ 'has-error' if form.name.errors }}">
                        {{ form.name.label(class_="col-md-4 control-label") }}
                        <div class="col-md-6">
                            {{ form.name(class_="form-control") }}
                            {% if form.name.errors %}
                            <span class="text-danger">
                                {% for error in form.name.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group {{ 'has-error' if form.password.errors }}">
                        {{ form.password.label(class_="col-md-4 control-label") }}
                        <div class="col-md-6">
                            {{ form.password(class_="form-control") }}
                            {% if form.password.errors %}
                            <span class="text-danger">
                                {% for error in form.password.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <button class="btn btn-primary" type="submit">Log in</button>
                        </div>
                    </div>
                </form>
                <div>
                    <p><em>Not yet registered? </em> <a href="{{ url_for('users.register') }}">Sign up!</a></p>
                </div>
            </div>
        </div>
    </div>   
</div>
{% endblock %}

project/templates/register.html
{% extends "_base.html" %}
{% block content %}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>Welcome to FlaskTaskr</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                Please register to access task list.
            </div>
            <div class="panel-body">
                <form action="" method="POST" class="form-horizontal">
                    {{ form.csrf_token }}
                    <div class="form-group {{ 'has-error' if form.name.errors }}">
                        {{ form.name.label(class_="col-md-4 control-label") }}
                        <div class="col-md-6">
                            {{ form.name(class_="form-control") }}
                            {% if form.name.errors %}
                            <span class="text-danger">
                                {% for error in form.name.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group {{ 'has-error' if form.email.errors }}">
                        {{ form.email.label(class_="col-md-4 control-label") }}
                        <div class="col-md-6">
                            {{ form.email(class_="form-control") }}
                            {% if form.email.errors %}
                            <span class="text-danger">
                                {% for error in form.email.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group {{ 'has-error' if form.password.errors }}">
                        {{ form.password.label(class_="col-md-4 control-label") }}
                        <div class="col-md-6">
                            {{ form.password(class_="form-control") }}
                            {% if form.password.errors %}
                            <span class="text-danger">
                                {% for error in form.password.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group {{ 'has-error' if form.confirm.errors }}">
                        {{ form.confirm.label(class_="col-md-4 control-label") }}
                        <div class="col-md-6">
                            {{ form.confirm(class_="form-control") }}
                            {% if form.confirm.errors %}
                            <span class="text-danger">
                                {% for error in form.confirm.errors %}
                                    {{ error }}
                                {% endfor %}
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-4">
                            <button class="btn btn-primary" type="submit">Register</button>
                        </div>
                    </div>
                </form>
                <div>
                    <p><em>Already registered?</em> Click <a href="{{ url_for('users.login') }}">here</a> to login.</p>
                </div>
            </div>
        </div>
    </div>   
</div>
{% endblock %}

project/templates/tasks.html
{% extends "_base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h3>Add a new task: {{ error }}</h3>
        <form class="form-inline" action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group {{ 'has-error' if form.name.errors }}">
                {{ form.name(class_="form-control", placeholder="Task name") }}
                {% if form.name.errors %}
                <span class="text-danger">
                    {% for error in form.name.errors %}
                        {{ error }}
                    {% endfor %}
                </span>
                {% endif %}
            </div>
            <div class="form-group {{ 'has-error' if form.due_date.errors }}">
                {{ form.due_date(class_="form-control", placeholder="Due date (dd/mm/yyyy)") }}
                {% if form.due_date.errors %}
                <span class="text-danger">
                    {% for error in form.due_date.errors %}
                        {{ error }}
                    {% endfor %}
                </span>
                {% endif %}
            </div>
            <div class="form-group {{ 'has-error' if form.priority.errors }}">
                {{ form.priority(class_="form-control", placeholder="Priority") }}
                {% if form.priority.errors %}
                <span class="text-danger">
                    {% for error in form.priority.errors %}
                        {{ error }}
                    {% endfor %}
                </span>
                {% endif %}
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Save</button>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h2>Open Tasks</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Due date</th>
                    <th>Posted date</th>
                    <th>Priority</th>
                    <th>Posted by</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for task in open_tasks %}
                <tr>
                    <td>{{ task.name }}</td>
                    <td>{{ task.due_date }}</td>
                    <td>{{ task.posted_date }}</td>
                    <td>{{ task.priority }}</td>
                    <td>{{ task.poster.name }}</td>
                    <td>
                        {% if task.poster.name == session.name or session.role == 'admin' %}
                        <a class="btn btn-xs btn-success" href="{{ url_for('tasks.complete', task_id = task.task_id) }}">Complete</a>
                        <a class="btn btn-xs btn-danger" href="{{ url_for('tasks.delete', task_id = task.task_id) }}">Delete</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <hr/>
    </div>
</div>
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h2>Closed Tasks</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Due date</th>
                    <th>Priority</th>
                    <th>Posted by</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for task in closed_tasks %}
                <tr>
                    <td>{{ task.name }}</td>
                    <td>{{ task.due_date }}</td>
                    <td>{{ task.priority }}</td>
                    <td>{{ task.poster.name }}</td>
                    <td>
                        {% if task.poster.name == session.name or session.role == 'admin' %}
                        <a class="btn btn-xs btn-danger" href="{{ url_for('tasks.delete', task_id = task.task_id) }}">Delete</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}